### ISSUE TITLE
Make a to-do list

### ISSUE THREAD

**Issue by brianjcook** [brianjcook/brianjcook.github.io#28]
- [x]  Create the list
- [x]  Mark something complete
- [x] Mark another thing complete
- [x] Make a comment
- [x] Close the issue

**Comment by brianjcook** [comment]
This is a comment.
